#!/usr/bin/env python3
"""Generate src/win-ref/font_kr.h from a BDF font (Galmuri9).

Embeds the 2350 KS X 1001 Hangul syllables as 10x12 bitmaps
(12 rows of uint16, LSB = leftmost pixel, baseline at row 10).

Usage:
    curl -sL -o /tmp/Galmuri9.bdf \
        https://github.com/quiple/galmuri/raw/main/dist/Galmuri9.bdf
    python3 tools/mkfont.py /tmp/Galmuri9.bdf > src/win-ref/font_kr.h

Galmuri font: Copyright (c) 2019-2025 Lee Minseo, SIL Open Font License 1.1
https://github.com/quiple/galmuri
"""
import sys

CELL_ROWS = 12
BASELINE = 10  # row index of the baseline inside the 12-row cell


def ks2350():
    """KS X 1001 syllables in EUC-KR order (lead 0xB0-0xC8, tail 0xA1-0xFE)."""
    out = []
    for lead in range(0xB0, 0xC9):
        for tail in range(0xA1, 0xFF):
            try:
                ch = bytes((lead, tail)).decode("euc-kr")
            except UnicodeDecodeError:
                continue
            cp = ord(ch)
            if 0xAC00 <= cp <= 0xD7A3:
                out.append(cp)
    assert len(out) == 2350, len(out)
    return sorted(out)


def parse_bdf(path, wanted):
    glyphs = {}
    with open(path, encoding="utf-8", errors="replace") as f:
        enc = None
        bbx = None
        rows = None
        for line in f:
            line = line.rstrip()
            if line.startswith("ENCODING "):
                enc = int(line.split()[1])
            elif line.startswith("BBX "):
                _, w, h, xo, yo = line.split()
                bbx = (int(w), int(h), int(xo), int(yo))
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if enc in wanted and bbx and rows is not None:
                    glyphs[enc] = (bbx, rows)
                enc, bbx, rows = None, None, None
            elif rows is not None:
                rows.append(int(line, 16))
    return glyphs


def to_cell(bbx, hexrows):
    """Place glyph into a 12-row cell, baseline at BASELINE. Returns uint16 rows."""
    w, h, xo, yo = bbx
    nbits = ((w + 7) // 8) * 8  # hex rows are byte-padded, MSB = leftmost
    cell = [0] * CELL_ROWS
    top = BASELINE - h - yo  # glyph top row inside cell
    for i, hv in enumerate(hexrows):
        r = top + i
        if not 0 <= r < CELL_ROWS:
            continue
        bits = 0
        for x in range(w):
            if hv & (1 << (nbits - 1 - x)):
                bits |= 1 << (x + xo)  # LSB = leftmost
        cell[r] = bits & 0xFFFF
    return cell


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    cps = ks2350()
    glyphs = parse_bdf(sys.argv[1], set(cps))
    missing = [cp for cp in cps if cp not in glyphs]
    if missing:
        sys.exit(f"missing {len(missing)} glyphs, e.g. U+{missing[0]:04X}")

    print("// Generated by tools/mkfont.py — do not edit.")
    print("// Hangul 10x12 bitmaps from Galmuri9 (OFL-1.1).")
    print("// Copyright (c) 2019-2025 Lee Minseo, https://github.com/quiple/galmuri")
    print("// 2350 KS X 1001 syllables, sorted by codepoint for bsearch.")
    print("// 12 rows per glyph, uint16, LSB = leftmost pixel, baseline row 10.")
    print("#pragma once")
    print("#include <stdint.h>")
    print()
    print(f"#define KFONT_N {len(cps)}")
    print(f"#define KFONT_ROWS {CELL_ROWS}")
    print()
    print("static const uint16_t g_kfont_cp[KFONT_N] = {")
    for i in range(0, len(cps), 12):
        print("    " + ", ".join(f"0x{cp:04X}" for cp in cps[i:i + 12]) + ",")
    print("};")
    print()
    print("static const uint16_t g_kfont[KFONT_N][KFONT_ROWS] = {")
    for cp in cps:
        cell = to_cell(*glyphs[cp])
        body = ",".join(f"0x{v:04X}" for v in cell)
        print(f"    {{{body}}}, // U+{cp:04X} {chr(cp)}")
    print("};")


if __name__ == "__main__":
    main()
